name: Deploy Sphinx documentation to Pages

on: [push, pull_request, workflow_dispatch]
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
          pip install sphinx sphinx_rtd_theme
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
